# Generated by Django 5.2 on 2025-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=30)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
